# Generated by Django 5.2.1 on 2025-05-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigibi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
